### ISSUE TITLE
【主页|课程列表页面】课程类型模块跳转

### ISSUE THREAD

**Issue by yxq199348** [sparrowflyer/jishu#41]
主页加入课程类型模块，跳转到课程列表页面，并显示对应课程类型数据。
![image](https://user-images.githubusercontent.com/11784229/51979820-16bca900-24c9-11e9-824b-7675fb8a4c2e.png)

**Comment by yxq199348** [comment]
@sparrowflyer 请测试，测试通过请关闭issue单，如果回归不通过，请assign给我

**Comment by sparrowflyer** [comment]
#41 购买前验证 #43 购买按钮，如果已经购买，直接显示已购买该课程，而不需要点击确认

**Comment by yxq199348** [comment]
> @sparrowflyer 请测试，测试通过请关闭issue单，如果回归不通过，请assign给我

> #41 购买前验证 #43 购买按钮，如果已经购买，直接显示已购买该课程，而不需要点击确认

服务器端提供的是单个课程购买前验证的接口，课程列表接口中没有是否已经购买的字段

**Comment by yxq199348** [comment]
@sparrowflyer 服务器端提供的是单个课程购买前验证的接口，课程列表接口中没有是否已经购买的字段
